remote_theme: witherslayer67/midnight@0.5.8
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

theme:
  custom_dir: 'imageAssets'
  favicon: /favicon.png
title: Lynk Library of Knowledge
description: 9496 Lynk's site for housing knowledge and information for the team.
