remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

theme:
  custom_dir: 'imageAssets'
  favicon: /favicon.png
title: Lynk Library of Knowledge
description: 9496 Lynk's site for housing knowledge and information for the team.

social-network-links:
  email: "info@lynkrobotics.org"
  facebook: LynkRobotics
  github: LynkRobotics

plugins:
  - jekyll-paginate
  - jekyll-sitemap