name: LLK Content Request
description: Request for content to be added to the LLK
title: "[Content Request]: "
labels: ["documentation"]
projects: ["LLK ToDo List/1"]
assignees:
  - witherslayer67
body:
  - type: textarea
    id: name-of-resource
    attributes:
      label: Name of Resource
      description: Whats the name of the resource?
      placeholder: Insert the name
      value: "Name!"
    validations:
      required: true
  - type: dropdown
    id: subteam
    attributes:
      label: SubTeam
      description: Which Subteam section does this resource belong to?
      options:
        - Build
        - Design
        - Electrical
        - Programming
        - Scouting
        - Strategy
        - What is FRC?
        - Technical Binders
        - Team Blogs
      default: 0
    validations:
      required: true
