name: LLK Content Request
description: Request for content to be added to the LLK
title: "[Content Request]: "
labels: ["documentation"]
projects: ["LynkRobotics/1"]
assignees:
  - witherslayer67
body:
  - type: input
    id: name-of-resource
    attributes:
      label: Name of Resource
      description: Whats the name of the resource?
      placeholder: "Resource Name"
    validations:
      required: true
  - type: input
    id: resourceLink
    attributes:
      label: Resource Link 1
      description: URL for the resource
      placeholder: "www.url.com/resource"
    validations:
      required: true
  - type: input
    id: resourceLink2
    attributes:
      label: Resource Link 2
      description: 2nd URL for the resource (like a video link)
      placeholder: "www.url.com/resource"
    validations:
      required: true
  - type: dropdown
    id: subteam
    attributes:
      label: Subteam
      description: Which Subteam section does this resource belong to?
      options:
        - Build
        - Design
        - Electrical
        - Programming
        - Scouting
        - Strategy
        - What is FRC?
        - Technical Reading
        - Technical Binders
        - Team Blogs
      multiple: true
    validations:
      required: true
  - type: dropdown
    id: contentLevel
    attributes:
      label: Level of content
      description: Which level does this resource belong to?
      options:
        - Do not know
        - Beginner
        - Intermediate
        - Advanced
        - Tools
        - Misc
    validations:
      required: true
  - type: dropdown
    id: readingVideo
    attributes:
      label: Reading / Video / Other
      description: Is this a reading, video, or other resource? 
      options:
        - Reading
        - Video
        - Other
      multiple: true
    validations:
      required: true
  - type: checkboxes
    id: haveChecked
    attributes:
      label: Have you checked if this resource is already in the LLK
      description: By submitting this issue, you have seen that this is not already provided in the LLK
      options:
        - label: I have checked
          required: true
