name: LLK Suggestion Form
description: Suggestion Form for the LLK
title: "[LLK Suggestion]: "
labels: ["improvement"]
projects: ["LynkRobotics/1"]
assignees:
  - witherslayer67
body:
  - type: textarea
    id: suggestion
    attributes: 
      label: Suggestion
      description: "What is your suggestion for the LLK?"
    validations:
      required: true
